plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running

# Dynamically group hosts by tag Name
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
  - key: platform
    prefix: os

hostnames:
  - private-ip-address

# Define user, connection, and other vars based on instance platform
compose:
  ansible_user: >
    {{
      'Administrator' if platform == 'windows'
      else 'ubuntu' if tags['OS'] == 'ubuntu'
      else 'ec2-user'
    }}
  ansible_password: >
    {{ 'P@ssw0rd' if platform == 'windows' else omit }}
  ansible_connection: >
    {{ 'winrm' if platform == 'windows' else 'ssh' }}
  ansible_port: >
    {{ 5985 if platform == 'windows' else 22 }}
  ansible_winrm_transport: >
    {{ 'ntlm' if platform == 'windows' else omit }}
  ansible_winrm_server_cert_validation: >
    {{ 'ignore' if platform == 'windows' else omit }}
