plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: win
hostnames:
  - private-ip-address
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
compose:
  ansible_user: "'Administrator'"
  ansible_password: "'P@ssw0rd'"
  ansible_connection: "'winrm'"
  ansible_port: 5985
  ansible_winrm_transport: "'ntlm'"
  ansible_winrm_server_cert_validation: "'ignore'"
