version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:v1
    ports: 
      - "8080:80"
    volumes:
      - mydata:/data
    networks:
      mynetwork:
    env_file:
      - my.env
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      retries: 3
      timeout: 5s

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16

volumes:
  mydata:
  depends_on: - db
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_DATABASE: "mydb"
            MYSQL_USER: "myuser"
            MYSQL_PASSWORD: "admin"
        ports:
            - "3306:3306"
        volumes: 
            - type: bind
              source: ./sqldata
              target: /dbdata
        restart: always
volumes:
    mydata:
    sqldata:
networks:
    mynetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0/16
