version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:v1
    ports: 
      - "8080:80"
    volumes:
      - mydata:/data
    networks:
      - mynetwork
    env_file:
      - my.env
    restart: always
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      retries: 3
      timeout: 5s

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes: 
      - ./sqldata:/dbdata
    restart: always

volumes:
  mydata:
  sqldata:

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
