# -------- BUILD STAGE --------
FROM ubuntu:22.04 AS build

RUN apt update && \
    apt install -y maven openjdk-17-jdk git

WORKDIR /app

RUN git clone https://github.com/vickeyys/spring-petclinic.git

WORKDIR /app/spring-petclinic

RUN mvn clean package -DskipTests

# -------- RUNTIME STAGE --------
FROM openjdk:17-alpine

WORKDIR /app

COPY --from=build /app/spring-petclinic/target/spring-petclinic-*.jar ./spring-petclinic.jar

CMD ["java", "-jar", "spring-petclinic.jar"]
