## create service account
apiVersion: v1
kind: ServiceAccount 
metadata:
  name: nginx-sa 
  namespace: default

---
### create role
apiVersion: rbac.authorization.k8s.io/v1
kind: role
metadata:
  name: read-only
  namespace: default 
rules: 
  - apiGroups: [""]
    resources: ["pods", "services"]
    verb: ["list", "watch", "get"]

---
# creaet rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  name: read-binding
  namespace: default 
subjects:
  - kind: ServiceAccount 
    name: nginx-sa 
    namespace: default
roleRef:
  - kind: role
    apiVersion: rbac.authorization.k8s.io/v1
    roleName: read-only

---
# nginx deployment with service account
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-sa  # ← Attach custom SA here
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
